package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Check generated by hbm2java
 */
public class Check implements java.io.Serializable {

	private Integer id;
	private String checkId;
	private String createBy;
	private String shelf;
	private Date checkDate;
	private Date createTime;
	private String status;
	private String remark;
	private Set<Goodscheck> goodschecks = new HashSet<Goodscheck>(0);

	public Check() {
	}

	public Check(String checkId, String createBy, String shelf, Date checkDate,
			Date createTime, String status) {
		this.checkId = checkId;
		this.createBy = createBy;
		this.shelf = shelf;
		this.checkDate = checkDate;
		this.createTime = createTime;
		this.status = status;
	}

	public Check(String checkId, String createBy, String shelf, Date checkDate,
			Date createTime, String status, String remark,
			Set<Goodscheck> goodschecks) {
		this.checkId = checkId;
		this.createBy = createBy;
		this.shelf = shelf;
		this.checkDate = checkDate;
		this.createTime = createTime;
		this.status = status;
		this.remark = remark;
		this.goodschecks = goodschecks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCheckId() {
		return this.checkId;
	}

	public void setCheckId(String checkId) {
		this.checkId = checkId;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getShelf() {
		return this.shelf;
	}

	public void setShelf(String shelf) {
		this.shelf = shelf;
	}

	public Date getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Goodscheck> getGoodschecks() {
		return this.goodschecks;
	}

	public void setGoodschecks(Set<Goodscheck> goodschecks) {
		this.goodschecks = goodschecks;
	}

}
