package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer id;
	private String customerName;
	private String city;
	private String address;
	private String postcode;
	private String contact;
	private String status;
	private String telphone;

	public Customer() {
	}

	public Customer(String customerName, String contact, String status) {
		this.customerName = customerName;
		this.contact = contact;
		this.status = status;
	}

	public Customer(String customerName, String city, String address,
			String postcode, String contact, String status, String telphone) {
		this.customerName = customerName;
		this.city = city;
		this.address = address;
		this.postcode = postcode;
		this.contact = contact;
		this.status = status;
		this.telphone = telphone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTelphone() {
		return this.telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

}
