package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Deliver generated by hbm2java
 */
public class Deliver implements java.io.Serializable {

	private Integer id;
	private String deliverId;
	private String createBy;
	private String city;
	private Date deliverDate;
	private String status;
	private String remark;
	private Set<Goodsdeliver> goodsdelivers = new HashSet<Goodsdeliver>(0);

	public Deliver() {
	}

	public Deliver(String deliverId, String createBy, String city,
			Date deliverDate, String status) {
		this.deliverId = deliverId;
		this.createBy = createBy;
		this.city = city;
		this.deliverDate = deliverDate;
		this.status = status;
	}

	public Deliver(String deliverId, String createBy, String city,
			Date deliverDate, String status, String remark,
			Set<Goodsdeliver> goodsdelivers) {
		this.deliverId = deliverId;
		this.createBy = createBy;
		this.city = city;
		this.deliverDate = deliverDate;
		this.status = status;
		this.remark = remark;
		this.goodsdelivers = goodsdelivers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDeliverId() {
		return this.deliverId;
	}

	public void setDeliverId(String deliverId) {
		this.deliverId = deliverId;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Date getDeliverDate() {
		return this.deliverDate;
	}

	public void setDeliverDate(Date deliverDate) {
		this.deliverDate = deliverDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Goodsdeliver> getGoodsdelivers() {
		return this.goodsdelivers;
	}

	public void setGoodsdelivers(Set<Goodsdeliver> goodsdelivers) {
		this.goodsdelivers = goodsdelivers;
	}

}
