package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Goodsstockout generated by hbm2java
 */
public class Goodsstockout implements java.io.Serializable {

	private Integer id;
	private Stockout stockout;
	private String productName;
	private String shelfName;
	private int qty;

	public Goodsstockout() {
	}

	public Goodsstockout(Stockout stockout, String productName,
			String shelfName, int qty) {
		this.stockout = stockout;
		this.productName = productName;
		this.shelfName = shelfName;
		this.qty = qty;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Stockout getStockout() {
		return this.stockout;
	}

	public void setStockout(Stockout stockout) {
		this.stockout = stockout;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getShelfName() {
		return this.shelfName;
	}

	public void setShelfName(String shelfName) {
		this.shelfName = shelfName;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

}
