package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Goodsstockin generated by hbm2java
 */
public class Goodsstockin implements java.io.Serializable {

	private Integer id;
	private Stockin stockin;
	private String productName;
	private String shelfName;
	private int qty;

	public Goodsstockin() {
	}

	public Goodsstockin(Stockin stockin, String productName, String shelfName,
			int qty) {
		this.stockin = stockin;
		this.productName = productName;
		this.shelfName = shelfName;
		this.qty = qty;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Stockin getStockin() {
		return this.stockin;
	}

	public void setStockin(Stockin stockin) {
		this.stockin = stockin;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getShelfName() {
		return this.shelfName;
	}

	public void setShelfName(String shelfName) {
		this.shelfName = shelfName;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

}
