package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Goodscheck generated by hbm2java
 */
public class Goodscheck implements java.io.Serializable {

	private Integer id;
	private Check check;
	private String productName;
	private int qty;
	private int checkQty;

	public Goodscheck() {
	}

	public Goodscheck(Check check, String productName, int qty, int checkQty) {
		this.check = check;
		this.productName = productName;
		this.qty = qty;
		this.checkQty = checkQty;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Check getCheck() {
		return this.check;
	}

	public void setCheck(Check check) {
		this.check = check;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public int getCheckQty() {
		return this.checkQty;
	}

	public void setCheckQty(int checkQty) {
		this.checkQty = checkQty;
	}

}
