package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Resources generated by hbm2java
 */
public class Resources implements java.io.Serializable {

	private Integer id;
	private String resourceName;
	private String comments;
	private String createTime;
	private String status;

	public Resources() {
	}

	public Resources(String resourceName, String createTime, String status) {
		this.resourceName = resourceName;
		this.createTime = createTime;
		this.status = status;
	}

	public Resources(String resourceName, String comments, String createTime,
			String status) {
		this.resourceName = resourceName;
		this.comments = comments;
		this.createTime = createTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
