package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Shelf generated by hbm2java
 */
public class Shelf implements java.io.Serializable {

	private Integer id;
	private String shelfName;
	private String comment;
	private String status;

	public Shelf() {
	}

	public Shelf(String shelfName, String status) {
		this.shelfName = shelfName;
		this.status = status;
	}

	public Shelf(String shelfName, String comment, String status) {
		this.shelfName = shelfName;
		this.comment = comment;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShelfName() {
		return this.shelfName;
	}

	public void setShelfName(String shelfName) {
		this.shelfName = shelfName;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
