package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stockin generated by hbm2java
 */
public class Stockin implements java.io.Serializable {

	private Integer id;
	private String stockInId;
	private Date stockInDate;
	private String stockInType;
	private String batchNo;
	private String createBy;
	private Date createTime;
	private String vendor;
	private String status;
	private String remark;
	private Set<Goodsstockin> goodsstockins = new HashSet<Goodsstockin>(0);

	public Stockin() {
	}

	public Stockin(String stockInId, Date stockInDate, String stockInType,
			String batchNo, String createBy, Date createTime, String vendor,
			String status) {
		this.stockInId = stockInId;
		this.stockInDate = stockInDate;
		this.stockInType = stockInType;
		this.batchNo = batchNo;
		this.createBy = createBy;
		this.createTime = createTime;
		this.vendor = vendor;
		this.status = status;
	}

	public Stockin(String stockInId, Date stockInDate, String stockInType,
			String batchNo, String createBy, Date createTime, String vendor,
			String status, String remark, Set<Goodsstockin> goodsstockins) {
		this.stockInId = stockInId;
		this.stockInDate = stockInDate;
		this.stockInType = stockInType;
		this.batchNo = batchNo;
		this.createBy = createBy;
		this.createTime = createTime;
		this.vendor = vendor;
		this.status = status;
		this.remark = remark;
		this.goodsstockins = goodsstockins;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockInId() {
		return this.stockInId;
	}

	public void setStockInId(String stockInId) {
		this.stockInId = stockInId;
	}

	public Date getStockInDate() {
		return this.stockInDate;
	}

	public void setStockInDate(Date stockInDate) {
		this.stockInDate = stockInDate;
	}

	public String getStockInType() {
		return this.stockInType;
	}

	public void setStockInType(String stockInType) {
		this.stockInType = stockInType;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Goodsstockin> getGoodsstockins() {
		return this.goodsstockins;
	}

	public void setGoodsstockins(Set<Goodsstockin> goodsstockins) {
		this.goodsstockins = goodsstockins;
	}

}
