package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stockout generated by hbm2java
 */
public class Stockout implements java.io.Serializable {

	private Integer id;
	private String stockOutId;
	private String stockOutType;
	private String createBy;
	private String customer;
	private Date createTime;
	private Date stockOutDate;
	private String status;
	private String remark;
	private Set<Goodsstockout> goodsstockouts = new HashSet<Goodsstockout>(0);

	public Stockout() {
	}

	public Stockout(String stockOutId, String stockOutType, String createBy,
			String customer, Date createTime, Date stockOutDate, String status) {
		this.stockOutId = stockOutId;
		this.stockOutType = stockOutType;
		this.createBy = createBy;
		this.customer = customer;
		this.createTime = createTime;
		this.stockOutDate = stockOutDate;
		this.status = status;
	}

	public Stockout(String stockOutId, String stockOutType, String createBy,
			String customer, Date createTime, Date stockOutDate, String status,
			String remark, Set<Goodsstockout> goodsstockouts) {
		this.stockOutId = stockOutId;
		this.stockOutType = stockOutType;
		this.createBy = createBy;
		this.customer = customer;
		this.createTime = createTime;
		this.stockOutDate = stockOutDate;
		this.status = status;
		this.remark = remark;
		this.goodsstockouts = goodsstockouts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStockOutId() {
		return this.stockOutId;
	}

	public void setStockOutId(String stockOutId) {
		this.stockOutId = stockOutId;
	}

	public String getStockOutType() {
		return this.stockOutType;
	}

	public void setStockOutType(String stockOutType) {
		this.stockOutType = stockOutType;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getStockOutDate() {
		return this.stockOutDate;
	}

	public void setStockOutDate(Date stockOutDate) {
		this.stockOutDate = stockOutDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Goodsstockout> getGoodsstockouts() {
		return this.goodsstockouts;
	}

	public void setGoodsstockouts(Set<Goodsstockout> goodsstockouts) {
		this.goodsstockouts = goodsstockouts;
	}

}
