package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String utype;
	private String deptName;
	private String email;
	private Date createTime;
	private String status;
	private String grantsManage;
	private Date lastLoginTime;

	public Users() {
	}

	public Users(String username, String password, String utype,
			String deptName, Date createTime, String status) {
		this.username = username;
		this.password = password;
		this.utype = utype;
		this.deptName = deptName;
		this.createTime = createTime;
		this.status = status;
	}

	public Users(String username, String password, String utype,
			String deptName, String email, Date createTime, String status,
			String grantsManage, Date lastLoginTime) {
		this.username = username;
		this.password = password;
		this.utype = utype;
		this.deptName = deptName;
		this.email = email;
		this.createTime = createTime;
		this.status = status;
		this.grantsManage = grantsManage;
		this.lastLoginTime = lastLoginTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUtype() {
		return this.utype;
	}

	public void setUtype(String utype) {
		this.utype = utype;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getGrantsManage() {
		return this.grantsManage;
	}

	public void setGrantsManage(String grantsManage) {
		this.grantsManage = grantsManage;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

}
