package bean;

// Generated 2013-6-8 23:00:05 by Hibernate Tools 3.4.0.CR1

/**
 * Vendor generated by hbm2java
 */
public class Vendor implements java.io.Serializable {

	private Integer id;
	private String vendorName;
	private String cityId;
	private String address;
	private String postcode;
	private String telephone;
	private String contact;
	private String status;

	public Vendor() {
	}

	public Vendor(String vendorName, String contact, String status) {
		this.vendorName = vendorName;
		this.contact = contact;
		this.status = status;
	}

	public Vendor(String vendorName, String cityId, String address,
			String postcode, String telephone, String contact, String status) {
		this.vendorName = vendorName;
		this.cityId = cityId;
		this.address = address;
		this.postcode = postcode;
		this.telephone = telephone;
		this.contact = contact;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
